export const STATUS = {
  cancelled: "cancelled",
  new: "new",
  active: "active",
  add_driver: "add_driver",
  start_driver: "start_driver",
  start_loading: "start_loading",
  verification_loading: "verification_loading",
  start_unloading: "start_unloading",
  verification_unloading: "verification_unloading",
  finished: "finished",
  deleted: "deleted",
  closed: "closed",
  verified_participant: "verified_participant",
  await_paid: "await_paid",
};
