export const mockLeads = [
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e201",
    num: 1,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Suleimenov Syrym",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, г Астана",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "*AKE Plast (АКЕ Пласт) ТОО",
    cargo: {
      description: "Груз заявки #33249585 1",
      weight_kg: 0,
      type: "Не указан",
    },
    description: "Груз заявки #33249585 1",
    context: null,
    weight_kg: 0,
    type: "Не указан",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e202",
    num: 2,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Aitbayev Nursultan",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, г Алматы",
    from_location: "Казахстан, Карагандинская обл",
    gsm: false,
    customer: "KazLogistics LTD",
    cargo: {
      description: "Груз заявки #33249585 2",
      weight_kg: 1200,
      type: "Паллеты",
    },
    description: "Груз заявки #33249585 2",
    context: null,
    weight_kg: 1200,
    type: "Паллеты",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e203",
    num: 3,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Bekzhanov Arman",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Шымкент",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "TransAsia Group",
    cargo: {
      description: "Груз заявки #33249585 3",
      weight_kg: 500,
      type: "Коробки",
    },
    description: "Груз заявки #33249585 3",
    context: null,
    weight_kg: 500,
    type: "Коробки",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e204",
    num: 4,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Ermekov Dias",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Астана",
    from_location: "Казахстан, Восточно-Казахстанская обл",
    gsm: true,
    customer: "LogiTrans KZ",
    cargo: {
      description: "Груз заявки #33249585 4",
      weight_kg: 800,
      type: "Металл",
    },
    description: "Груз заявки #33249585 4",
    context: null,
    weight_kg: 800,
    type: "Металл",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e205",
    num: 5,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Sadykov Timur",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Костанай",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "Global Cargo",
    cargo: {
      description: "Груз заявки #33249585 5",
      weight_kg: 300,
      type: "Техника",
    },
    description: "Груз заявки #33249585 5",
    context: null,
    weight_kg: 300,
    type: "Техника",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e206",
    num: 6,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Nurgaliyev Askar",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Павлодар",
    from_location: "Казахстан, Алматы обл",
    gsm: true,
    customer: "East Logistics",
    cargo: {
      description: "Груз заявки #33249585 6",
      weight_kg: 1500,
      type: "Стройматериалы",
    },
    description: "Груз заявки #33249585 6",
    context: null,
    weight_kg: 1500,
    type: "Стройматериалы",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e207",
    num: 7,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Kenzhebekov Alikhan",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Тараз",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "Steppe Cargo",
    cargo: {
      description: "Груз заявки #33249585 7",
      weight_kg: 700,
      type: "Оборудование",
    },
    description: "Груз заявки #33249585 7",
    context: null,
    weight_kg: 700,
    type: "Оборудование",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e208",
    num: 8,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Urazbaev Marat",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Атырау",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "OilTrans KZ",
    cargo: {
      description: "Груз заявки #33249585 8",
      weight_kg: 2000,
      type: "Нефтехимия",
    },
    description: "Груз заявки #33249585 8",
    context: null,
    weight_kg: 2000,
    type: "Нефтехимия",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e209",
    num: 9,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Serikbayev Nurlan",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Актау",
    from_location: "Казахстан, Павлодарская обл",
    gsm: true,
    customer: "West Cargo",
    cargo: {
      description: "Груз заявки #33249585 9",
      weight_kg: 600,
      type: "Продукты",
    },
    description: "Груз заявки #33249585 9",
    context: null,
    weight_kg: 600,
    type: "Продукты",
    volume_cm: null,
  },
  {
    status: "started",
    id: "6a0bf228b87b6aa6ad0445e210",
    num: 10,
    created_at: {
      date: "2026-05-19 05:16:24.059000",
      timezone_type: 3,
      timezone: "UTC",
    },
    driver: "Zhakupov Daniyar",
    summ: 0,
    currency: "KZT",
    transportation_price: 0,
    vat: "с НДС",
    to_location: "Казахстан, Алматы",
    from_location: "Казахстан, Павлодарская обл",
    gsm: false,
    customer: "KZ Express",
    cargo: {
      description: "Груз заявки #33249585 10",
      weight_kg: 950,
      type: "Сборный груз",
    },
    description: "Груз заявки #33249585 10",
    context: null,
    weight_kg: 950,
    type: "Сборный груз",
    volume_cm: null,
  },
];
